name: Release Docker image

run-name: Release ${{ github.ref_name }}

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v0.0.0-dev.*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        id: tag
        run: |
          is_dev=${{ startsWith(github.ref_name, 'v0.0.0-dev.') }}
          echo "is_dev=$is_dev" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set image metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: mattsyms/wait-for-it
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}},enable=${{ steps.tag.outputs.is_dev == 'false' }}
            type=semver,pattern={{major}},enable=${{ steps.tag.outputs.is_dev == 'false' }}
            type=raw,value=latest,enable=${{ steps.tag.outputs.is_dev == 'false' }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish to Docker Hub
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.metadata.outputs.tags }}

      - name: Update Docker Hub description
        if: steps.tag.outputs.is_dev == 'false'
        uses: peter-evans/dockerhub-description@v3
        with:
          repository: mattsyms/wait-for-it
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          short-description: ${{ github.event.repository.description }}
