name: Unrelease Docker image

run-name: Unrelease ${{ inputs.tag }}

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag
        default: v0.0.0
        required: true

jobs:
  unrelease:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        id: tag
        run: |
          tag=${{ inputs.tag }}
          version=${tag:1}
          echo "tag=$tag" >> $GITHUB_OUTPUT
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v3

      - name: Delete tag
        run: git push --delete origin ${{ steps.tag.outputs.tag }}

      - name: Login to Docker Hub
        id: login
        run: |
          token=$(curl --no-progress-meter \
            -X POST \
            -H 'Content-Type: application/json' \
            -d '{"username": "${{ secrets.DOCKERHUB_USER }}", "password": "${{ secrets.DOCKERHUB_TOKEN }}"}' \
            https://hub.docker.com/v2/users/login | jq -r .token)
          echo "token=$token" >> $GITHUB_OUTPUT

      - name: Unpublish from Docker Hub
        run: |
          curl --no-progress-meter \
            -X DELETE \
            -H 'Authorization: JWT ${{ steps.login.outputs.token }}' \
            https://hub.docker.com/v2/repositories/mattsyms/wait-for-it/tags/${{ steps.tag.outputs.version }}
